//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNMPv2-CONF DEFINITIONS ::= BEGIN
        ///
        ///IMPORTS ObjectName, NotificationName, ObjectSyntax
        ///                                               FROM SNMPv2-SMI;
        ///
        ///-- definitions for conformance groups
        ///
        ///OBJECT-GROUP MACRO ::=
        ///BEGIN
        ///    TYPE NOTATION ::=
        ///                  ObjectsPart
        ///                  &quot;STATUS&quot; Status
        ///                  &quot;DESCRIPTION&quot; Text
        ///                  ReferPart
        ///
        ///    VALUE NOTATION ::=
        ///                  value(VALUE OBJECT IDENTIFIER)
        ///
        ///    ObjectsPart ::=
        ///                  &quot;OBJECTS&quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_CONF {
            get {
                return ResourceManager.GetString("SNMPv2_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNMPv2-MIB DEFINITIONS ::= BEGIN
        ///
        ///IMPORTS
        ///    MODULE-IDENTITY, OBJECT-TYPE, NOTIFICATION-TYPE,
        ///    TimeTicks, Counter32, snmpModules, mib-2
        ///        FROM SNMPv2-SMI
        ///    DisplayString, TestAndIncr, TimeStamp
        ///
        ///        FROM SNMPv2-TC
        ///    MODULE-COMPLIANCE, OBJECT-GROUP, NOTIFICATION-GROUP
        ///        FROM SNMPv2-CONF;
        ///
        ///snmpMIB MODULE-IDENTITY
        ///    LAST-UPDATED &quot;200210160000Z&quot;
        ///    ORGANIZATION &quot;IETF SNMPv3 Working Group&quot;
        ///    CONTACT-INFO
        ///            &quot;WG-EMail:   snmpv3@lists.tislabs.com
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_MIB {
            get {
                return ResourceManager.GetString("SNMPv2_MIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SNMPV2_PDU {
            get {
                object obj = ResourceManager.GetObject("SNMPV2_PDU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNMPv2-SMI DEFINITIONS ::= BEGIN
        ///
        ///-- the path to the root
        ///
        ///org            OBJECT IDENTIFIER ::= { iso 3 }  --  &quot;iso&quot; = 1
        ///dod            OBJECT IDENTIFIER ::= { org 6 }
        ///internet       OBJECT IDENTIFIER ::= { dod 1 }
        ///
        ///directory      OBJECT IDENTIFIER ::= { internet 1 }
        ///
        ///mgmt           OBJECT IDENTIFIER ::= { internet 2 }
        ///mib-2          OBJECT IDENTIFIER ::= { mgmt 1 }
        ///transmission   OBJECT IDENTIFIER ::= { mib-2 10 }
        ///
        ///experimental   OBJECT IDENTIFIER ::= { internet 3 }
        ///
        ///private        OBJECT I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_SMI {
            get {
                return ResourceManager.GetString("SNMPv2_SMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNMPv2-TC DEFINITIONS ::= BEGIN
        ///
        ///IMPORTS
        ///    TimeTicks         FROM SNMPv2-SMI;
        ///
        ///-- definition of textual conventions
        ///
        ///TEXTUAL-CONVENTION MACRO ::=
        ///
        ///BEGIN
        ///    TYPE NOTATION ::=
        ///                  DisplayPart
        ///                  &quot;STATUS&quot; Status
        ///                  &quot;DESCRIPTION&quot; Text
        ///                  ReferPart
        ///                  &quot;SYNTAX&quot; Syntax
        ///
        ///    VALUE NOTATION ::=
        ///                   value(VALUE Syntax)      -- adapted ASN.1
        ///
        ///    DisplayPart ::=
        ///                  &quot;DISPLAY-HINT&quot; Text
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_TC {
            get {
                return ResourceManager.GetString("SNMPv2_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNMPv2-TM DEFINITIONS ::= BEGIN
        ///
        ///IMPORTS
        ///    MODULE-IDENTITY, OBJECT-IDENTITY,
        ///    snmpModules, snmpDomains, snmpProxys
        ///        FROM SNMPv2-SMI
        ///    TEXTUAL-CONVENTION
        ///        FROM SNMPv2-TC;
        ///
        ///snmpv2tm MODULE-IDENTITY
        ///    LAST-UPDATED &quot;200210160000Z&quot;
        ///    ORGANIZATION &quot;IETF SNMPv3 Working Group&quot;
        ///    CONTACT-INFO
        ///            &quot;WG-EMail:   snmpv3@lists.tislabs.com
        ///             Subscribe:  snmpv3-request@lists.tislabs.com
        ///
        ///             Co-Chair:   Russ Mundy
        ///                         Network Assoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPv2_TM {
            get {
                return ResourceManager.GetString("SNMPv2_TM", resourceCulture);
            }
        }
    }
}
